# goal
geographic_msgs/GeoPoseStamped target
---
# result
bool ok # flag indicating that hover ended for non-error reasons (i.e. user request)
---
# feedback
float32 range
float32 bearing
float32 speed
